## mutation library parameters ------------------------------------------------------

# patient sample ids
patient_ids:
  [P1]

# cell and umi barcode base positions in barcode reads for each sample. the first element of the
# array is the cell barcode range, while the second is the UMI barcode range.
bc_structure:
  10x_v3: [1-16, 17-28]

# reference files for alignment and annotation
genome_references:
  fasta: */Homo_sapiens.GRCh38.dna.primary_assembly.fasta
  genome_dir: "*/GRCh38/genomeDir"
  gtf: */Homo_sapiens.GRCh38.100.chr.gtf
  dict: */Homo_sapiens.GRCh38.dna.primary_assembly.dict
  refFlat: */Homo_sapiens.GRCh38.dna.primary_assembly.refFlat

# parameters read alignment ------------------------------------------------------------------------------
tag_cell_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

tag_molecule_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

trim_starting_sequence:
  adapter_sequence: AAGCAGTGGTATCAACGCAGAGTGAATGGG
  mismatches: 0
  num_bases: 5

trim_polyA:
  mismatches: 0
  num_bases: 6

star_align:
  threads_split_bams: 1
  threads_comp_bam: 8

bead_synthesis_error:
  min_umis_per_cell: 25
  max_num_errors: 1
  read_mq: 10
  primer_sequence: null
  edit_distance: 0

reads_per_cell:
  read_quality: 10

# params count_table
count_table:
  missmatch_ratio: 0.4
  min_umis_mutant: 1

# params read deduplicationn ------------------------------------------------------------
read_deduplication:
  max_open_files: 10000
  cores_split_files: 4
  umi_errors: 0
  min_reads_umi: 2
  star_threads: 1
  cores_merge_bam: 4
