## mutation library parameters ------------------------------------------------------

# patient sample ids
patient_ids:
  # get the present barcodes does not work with 10x BAM files...
  #[P80_WT, AKLA1b_WT, AKLK1_WT, AKLW1_WT]
  [P266_TAPseq, P266_spiked, AKLK1, AKLK2, AKLW1, AKLW2, AKLA1b, AKLA2, P80, P324, P186, P361, P19003_1, P221, P270]

# patients for which exome we have we can import selected_variants automatically
patient_exome:
  [P80, P186, P361, P270]

# estimated number of cells per sample, for which dge data should be extracted.
cell_numbers:
  P266_TAPseq: 4000
  P266_spiked: 4000
  AKLW1: 8000
  AKLW2: 8000
  AKLA1b: 8000
  AKLA2: 8000
  AKLK1: 8000
  AKLK2: 8000
  P80: 3000
  P324: 1000

# cell and umi barcode base positions in barcode reads for each sample. the first element of the
# array is the cell barcode range, while the second is the UMI barcode range.
bc_structure:
  10x_v3: [1-16, 17-28]


# reference files for alignment and annotation
genome_references:
  genome_dir: ../../../sbeneyto/alignment_references/GRCh38/genomeDir
  gtf: ../../../sbeneyto/alignment_references/GRCh38/Homo_sapiens.GRCh38.100.chr.gtf
  fasta: ../../../sbeneyto/alignment_references/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fasta
  dict: ../../../sbeneyto/alignment_references/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.dict
  refFlat: ../../../sbeneyto/alignment_references/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.refFlat
  bwa_genome: ../../../sbeneyto/alignment_references/hg38/hg38.fa


# parameters read alignment ------------------------------------------------------------------------------
tag_cell_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

tag_molecule_barcodes:
  base_quality: 10
  num_bases_below_quality: 1

trim_starting_sequence:
  adapter_sequence: AAGCAGTGGTATCAACGCAGAGTGAATGGG
  mismatches: 0
  num_bases: 5

trim_polyA:
  mismatches: 0
  num_bases: 6

star_align:
  threads_split_bams: 1
  threads_comp_bam: 8

bead_synthesis_error:
  min_umis_per_cell: 25
  max_num_errors: 1
  read_mq: 10
  primer_sequence: null
  edit_distance: 0

reads_per_cell:
  read_quality: 10

# params count_table
count_table:
  missmatch_ratio: 0.4
  min_umis_mutant: 1
  
# params read deduplicationn ------------------------------------------------------------
read_deduplication:
  max_open_files: 10000
  cores_split_files: 8
  umi_errors: 0
  min_reads_umi: 2
  star_threads: 1
  cores_merge_bam: 8

# path where barcodes and count matrices from 10x are stored
#10x_path: ../gene_expression/data/
